# Generated by Django 4.1 on 2022-10-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_quantity', models.IntegerField()),
                ('book_gener', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
